### ISSUE TITLE
Baseline error but amplification curve shows straight log-linear phase

### ISSUE THREAD

**Issue by dwightkuo** [RDML-consortium/rdmlpython#2] opened 2022-03-03 05:38 UTC
I noticed this in the LinRegPCR documentation:
> LinRegPCR reports a lot of baseline errors but the amplification curves show a straight log-linear phase.
LinRegPCR reports a baseline error when it is not possible to find a baseline value that leads to a straight
continuous set of data points in the log-linear phase. However, the program also reports a baseline error when the
remaining log-linear phase is to short. This may be because measurement noise causes the lower data points to be
discontinuous: the fluorescence in cycle c is larger than that in cycle c+1. The baseline estimation only uses data
in which Fc < Fc+1. In version 11.3 you can 'relax' this continuity criterion and allow jumps, as long as all data in
the log-linear phase are around a straight line. This leads to less baseline-error samples but also leads to more
variation between individual efficiency values.

I presume this is not supported in rdmlpython? Is there a more detailed description of exactly what this functionality does?

**Comment by ppreshant** [comment] 2022-03-08 02:35
On a related note, I have the same problem with baseline errors for very early amplifications but have a straight log-linear phase. The program might work if it just uses 0 or the first cycle's fluorescence as the baseline with some user input (with mention of it in the note). Would that make sense?

![baseline-error_q20b](https://user-images.githubusercontent.com/14856479/157154767-078eea68-608a-452c-96e0-45a8c687c1ac.png)

The image shows two different samples that are very close except for the shape of the first 1-3 cycles that one of them has a baseline error

For context: I have samples with 16s rRNA and two other targets (_with much lesser abundance_) I am measuring in triplex reactions. So I cannot dilute the sample to delay the 16s amplifications without loosing the rarer sample.

**Comment by dwightkuo** [comment] 2022-03-08 04:34
I've found that if I comment out line 11746:
> vecBaselineError[oRow] = True 

I at least get a Cq call rather than a baseline error

**Comment by ppreshant** [comment] 2022-03-11 16:46
Thank you! I'll try that and also if I can fix a baseline

**Comment by untergasser** [comment] 2022-03-12 04:10
Hi,

in LinRegPCR it is essential to find the correct baseline by linear regression. It needs to detect the shift from overestimation to underestimation, else it gives a baseline error. If you comment this out, you will get random values as result and calculate wrong results.

If you have examples where it goes wrong, send me the rdml file and the reaction numbers and I will have a look if it can be improved. The relax criterion is not implemented, lets see first if this is a bug or if we need to implement it.

Best,

Andreas

**Comment by dwightkuo** [comment] 2022-03-12 04:27
Hi Andreas,

I've attached an example which I renamed "temp.zip" as Github doesn't allow attaching files with rdml extension. An example of a well with this baseline / no amplification issue is well "A12"

[temp.zip](https://github.com/RDML-consortium/rdmlpython/files/8237061/temp.zip)
 
Thanks,
Dwight

**Comment by untergasser** [comment] 2022-03-20 07:50
Hi Dwight,

again your test data were really helpful.

This bug was more complex and the correction of negative values was fixed in version 1.4.0 just pushed to GitHub.
In this version you can specify --includeInstableBaseline to inactivate the check.

@[ppreshant](https://github.com/ppreshant) The first 10 cycles should not have an increase, so I am not sure if it works. I would need example data to check if it causes problems.

Dwight, can you check from GitHub that it solves this bug for you?

Best,

Andreas

**Comment by dwightkuo** [comment] 2022-03-21 04:44
Hi Andreas,

Version 1.4.0 with --includeInstableBaseline does indeed rescue many of the curves in our datasets. But comparing with previous Cq calls, there seems to be an increase of up to 1-2 Cqs for some curves. I've attached a scatter plot of ~3000 Cq calls comparing with and without --includeInstableBaseline.

![Picture1](https://user-images.githubusercontent.com/22648143/159206429-d4cce368-2e88-43c3-a678-d1b3310aafda.png)

Is this to be expected?

Thanks,
Dwight

**Comment by untergasser** [comment] 2022-03-21 05:50
Hi Dwight,

the Cq depend on the threshold and that may change. Did the N0 also change? Can you check?

Best,

Andreas

**Comment by dwightkuo** [comment] 2022-03-22 20:38
We use Cq since we're running standard curves so I haven't checked the N0s. I just checked the coefficient of variation for replicate Cqs and these do seem to decrease with v1.4.0 compared with the previous version. Thanks!

**Comment by untergasser** [comment] 2022-04-02 06:41
Hi Dwight,

we modified the baseline algorithm again in version 1.5.0. Could you again check that you still get good results?

Best,

Andreas

**Comment by ppreshant** [comment] 2022-04-04 08:14
> @[ppreshant](https://github.com/ppreshant) The first 10 cycles should not have an increase, so I am not sure if it works. I would need example data to check if it causes problems.

Hi Andreas,

 Thanks for the response. The newer version 1.5.0 seems to do much better with my early amplifications. There is still a few that are missing baseline but that might be inevitable (_wells: B9, E8, H8_). I attached the RDML file if you would want to check.

I might try to change the primer concentrations to see if that delays the amplification maybe?

[q25_S037_RAM repression_14-2-22fixpython.zip](https://github.com/RDML-consortium/rdmlpython/files/8407917/q25_S037_RAM.repression_14-2-22fixpython.zip)

Thanks,
Prashant

**Comment by dwightkuo** [comment] 2022-04-05 17:52
Hi Andreas,

We've found some samples with strange results in versions 1.3.0 1.4.1, and
1.5.0 compared to other algorithms. I've attached the RDML and show a
comparison plot.

Thanks,
Dwight

**Comment by untergasser** [comment] 2022-04-06 07:51
Hi Dwight,

somehow the attachments got lost. Can you send them again?

Best,

Andreas

**Comment by dwightkuo** [comment] 2022-04-06 14:54
Looks like attachments don't get properly handled when replying by email. I've attached the files to this comment:

![A67FDFDE4BFB48928BC6F4C8470FF7B2](https://user-images.githubusercontent.com/22648143/162003732-6bc07fbb-f7c9-4358-a255-1ac2e5d04beb.png)
[example.zip](https://github.com/RDML-consortium/rdmlpython/files/8428037/example.zip)

**Comment by dwightkuo** [comment] 2022-04-08 04:25
> Hi Dwight,
> 
> we modified the baseline algorithm again in version 1.5.0. Could you again check that you still get good results?
> 
> Best,
> 
> Andreas

Hi Andreas,

Compared with v1.4.1, v1.5 has marginally worse CV, marginally better linearity for dilution series, but slightly more NaNs. Overall, based on our existing dataset we will likely continue using 1.4.1 due to fewer NaNs

**Comment by untergasser** [comment] 2022-10-22 07:46
> > @[ppreshant](https://github.com/ppreshant) The first 10 cycles should not have an increase, so I am not sure if it works. I would need example data to check if it causes problems.
> 
> Hi Andreas,
> 
> Thanks for the response. The newer version 1.5.0 seems to do much better with my early amplifications. There is still a few that are missing baseline but that might be inevitable (_wells: B9, E8, H8_). I attached the RDML file if you would want to check.
> 
> I might try to change the primer concentrations to see if that delays the amplification maybe?
> 
> [q25_S037_RAM repression_14-2-22fixpython.zip](https://github.com/RDML-consortium/rdmlpython/files/8407917/q25_S037_RAM.repression_14-2-22fixpython.zip)
> 
> Thanks, Prashant

This file does not work as the concentrations are to high. LinRegPCR requires a ground phase to do the PCR efficiency estimation. This is failing here.

Best,

Andreas

**Comment by untergasser** [comment] 2022-10-22 08:01
> Looks like attachments don't get properly handled when replying by email. I've attached the files to this comment:
> 
> ![A67FDFDE4BFB48928BC6F4C8470FF7B2](https://user-images.githubusercontent.com/22648143/162003732-6bc07fbb-f7c9-4358-a255-1ac2e5d04beb.png) [example.zip](https://github.com/RDML-consortium/rdmlpython/files/8428037/example.zip)

Thank you so much for sending us this file (and the file in the other thread). You found a logical error in our algorithm which was fixed in version 1.6.0:
https://github.com/RDML-consortium/rdmlpython/commit/04b7c40e8ec10bf95b1514c595145c6f76fd8382

I am sorry that the fix took so long. The problem only rises with special curve shapes, a Cq above 25 and an constant increase of the baseline. Then all cycles were used to estimate the efficiency over the entire curve and the algorithm got it wrong. Now we limit the numbers of cycles in the log phase to 12 and the issue is gone. Your data was essential to understand why this was happening. Thank you very much!

Best,

Andreas

**Comment by ppreshant** [comment] 2022-10-27 02:53
> This file does not work as the concentrations are to high. LinRegPCR requires a ground phase to do the PCR efficiency estimation. This is failing here.
> Andreas

That makes sense. Thank you for the response. 
Would you recommend anything other than diluting the sample to help in this scenario?

**Comment by untergasser** [comment] 2023-03-05 16:12
I would go for dilutions... or other targets which are lower copy...

Best,
Andreas

**Comment by ppreshant** [comment] 2023-03-10 14:47
> I would go for dilutions... or other targets which are lower copy...
> 
> Best, Andreas

Makes sense. Thank you for the reply

**Closed as completed** 2023-05-22 15:10 UTC
