### ISSUE TITLE
Cq Discrepancy Between Replicate Runs

### ISSUE THREAD

**Issue by dwightkuo** [RDML-consortium/rdmlpython#4] opened 2022-04-28 16:14 UTC
For some reason many of the samples between these two runs (which are full-plate replicates) show a ~1.5 Cq difference despite the curves being very similar. While I understand that Cq should not be used directly for comparisons across difference plates, it was concerning that other qPCR methods we tried did not seem to have this same issue when comparing these plates. As an example, the A3 well has a Cq of 26.38 in plate1 and 24.83 in plate2. 

The numbers quoted were run with version 1.4.1, but I also see this issue with 1.5.1 as well. I've attached the rdml files

[plate2.zip](https://github.com/RDML-consortium/rdmlpython/files/8584441/plate2.zip)
[plate1.zip](https://github.com/RDML-consortium/rdmlpython/files/8584442/plate1.zip)

Any suggestions would be appreciated. Thanks!

**Comment by dwightkuo** [comment] 2022-06-22 20:52
Attaching another example where curves that look virtually identical but have discrepant Cq calls (wells G3 and G4 in the Texas Red channel). Looks to be some sort of issue with the background subtraction

[example.zip](https://github.com/RDML-consortium/rdmlpython/files/8961206/example.zip)

**Comment by untergasser** [comment] 2022-06-25 07:13
Hi,

thank you for the examples. You are right, the algorithm does not identify the correct baseline in this example. I will have a look into this in a few weeks, as I have to finish a different project first.

Best,
Andreas

**Comment by untergasser** [comment] 2022-10-22 08:03
> Attaching another example where curves that look virtually identical but have discrepant Cq calls (wells G3 and G4 in the Texas Red channel). Looks to be some sort of issue with the background subtraction
> 
> [example.zip](https://github.com/RDML-consortium/rdmlpython/files/8961206/example.zip)

Thank you so much for sending us this file (and the file in the other thread). You found a logical error in our algorithm which was fixed in version 1.6.0:
https://github.com/RDML-consortium/rdmlpython/commit/04b7c40e8ec10bf95b1514c595145c6f76fd8382

I am sorry that the fix took so long. The problem only rises with special curve shapes, a Cq above 25 and an constant increase of the baseline. Then all cycles were used to estimate the efficiency over the entire curve and the algorithm got it wrong. Now we limit the numbers of cycles in the log phase to 12 and the issue is gone. Your data was essential to understand why this was happening. Thank you very much!

Best,

Andreas

**Comment by untergasser** [comment] 2022-10-22 08:15
> For some reason many of the samples between these two runs (which are full-plate replicates) show a ~1.5 Cq difference despite the curves being very similar. While I understand that Cq should not be used directly for comparisons across difference plates, it was concerning that other qPCR methods we tried did not seem to have this same issue when comparing these plates. As an example, the A3 well has a Cq of 26.38 in plate1 and 24.83 in plate2.
> 
> The numbers quoted were run with version 1.4.1, but I also see this issue with 1.5.1 as well. I've attached the rdml files
> 
> [plate2.zip](https://github.com/RDML-consortium/rdmlpython/files/8584441/plate2.zip) [plate1.zip](https://github.com/RDML-consortium/rdmlpython/files/8584442/plate1.zip)
> 
> Any suggestions would be appreciated. Thanks!

With version 1.6 I get for plate 1, tex red amp a Cq 25.819 and N0 1.41e-3, with plate2 a Cq 26.018 and N0 1.50e-3. That looks fine to me. Cq values depend on PCR efficiency and  the threshold which might differ between plates. Plate differences are also expected, you can use InterRunCorrection to level them out:
https://www.gear-genomics.com/rdml-tools/analyze.html

Please let me know if you can recreate the differences looking at N0 values in version1.6.0. Then I would have a second look.

Best,
Andreas

**Closed as completed** 2023-03-05 16:11 UTC
